sudo: required
dist: xenial

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: CNpekncc7932A18BHB1i10HU+G8WuYKKiC6Zi/V5dDQ/+QgOOJcHkOjk0WevdVX813V/ZvmHWdZy338JMM6DnCQHC5goASEqxRTm+YypOyL+wfAg/6RSgh0bGpKer5mrLEZGzI6rooTDx45BVuREo0IfDV1R0Z8FUl2e3gbdS5XgIQWPY127thFCbkxN1+gXWPH+wYlmwyl4jZXKstD+myKmmnN3mgg8SpS3rbIAEVz0QHClyPwFzYGN03G7DuwF5OSfurqifaQclHLv1NMK6H7verY8RmvEBziMWX0Bi2HTRRpN2f2iV1IdCq+yy0UmQfWwa+v7w/QXCZgwoM1gyQFuHXzT8ESuX3KMjvD8w5VuKZX1zR3aU4EI0DCC3C11OeC1EGNku1A6Ev+0axVOQwqksIGhMpPHQXpu7oYjUm9duboHEwwsQ7dDCUP0yjOu9cEx6WLDR1zvjSDcFdlrs9Q/5v1ViBKx5oUef/4QEunDzNBT3BecGhTHdJC/I1G3I3BFkPlkEgx5rCyoROQu/A0VbVdpx83Y5AyKZAYhQUBmFUixaPfT5OEKHZI4fElY/m4a1zls2PcxHqQqjr8lbWtgXabXgqFUZbEs2uUmX2eMHnF+0GwpvrJCPHHa87Mi3TKPMgp+ankIq36jeyW4P0EsVVeHlCbOg2UOp9FbYwo=

branches:
  only:
  - master
  - develop
  - /^develop-.*/

addons:
  apt:
    config:
      retries: true
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gcc-7
      - g++-7
      - cmake
      - cmake-data
      - libcurl4-openssl-dev # required to avoid SSL errors

matrix: 
  include:       
  - language: c++
    os: linux
    compiler: clang
    script: ./build.sh

  - language: c++
    os: linux
    compiler: gcc
    script: ./build.sh 

  - language: ruby
    rvm: 2.7.0
    
    install: gem install jekyll html-proofer github-pages
    script: 
      - bundle install
      - bundle exec jekyll build && htmlproofer --http-status-ignore 0 ./_site
    env:
      global:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    sudo: false
