source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-redirect-from', group: [:jekyll_plugins]
gem 'jekyll-compose', group: [:jekyll_plugins]
gem "jekyll-remote-theme", group: [:jekyll_plugins]
gem 'jekyll-theme-adobe-hyde', path: '../../../stlab/hyde-theme'
