set( stlab_base_flags "-Wall;-ftemplate-backtrace-limit=0;" )
set( stlab_debug_flags "-gdwarf-3;" )
set( stlab_coverage_flags "-fprofile-arcs;-ftest-coverage;" )
set( stlab_release_flags "" )
set( stlab_interface_flags "-std=c++14;")
